version: '3.7'

services:

  # The application
  app:
    build:
      context: .
    image: &app app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: >
      sh -c 'watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db

  # Database
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "7777:7777"
