# Generated by Django 3.2.8 on 2021-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookCook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
